title: Below & Above the Clouds
author: Donovan Johnson
email: cloudstrategist@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A strategic view at modern solution design and delivery from a Datacenter & Cloud Guy who's an Entrepreneur, Enterprise Architect, Product Manager & still
  hands on. I discuss all things DC & Cloud related including but not limited to: Micro-datacenter/HomeLab setup, Power, Fault Domains, Physical networking, 
  SDN, microsegmenation, orchestration, service catalog development, CI/CD pipelines, DevOps, DevSecOps, Python Software Development, Azure, AWS, GCP, AzureDevOps, 
  Visual Studio, Cloud9, Enterprise Architecture, Solution Architecture, Technology & Infrastucture Architecture, Software Architecture, Lean Process Improvement 
  Scaled Agile Framework, and of course, Technology Strategy.
 

# social links
twitter_username: vDreamArkitex
github_username:  vDreamArkitex

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima  
